appName: "BroncoMexico"
imageName: "chrisgallivan/automate-all-the-things-docker"
environments: 
  - name: dev
    credentialId: DryRun
platform: "N/A"
terraform: true
emailList: ""
hangoutsToken: "vCgad3N0mJFW-ryyFWCEx0jM2"
